from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login_view, name='login'),
    path('admin/login/', views.admin_login_view, name='admin_login'),
    path('admin/signup/', views.admin_signup_view, name='admin_signup'),
    path('employee/login/', views.employee_login_view, name='employee_login'),
    path('manager/login/', views.manager_login_view, name='manager_login'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('admin/', views.admin_view, name='admin'),
    path('admin/add-user/', views.add_user_view, name='add_user'),
    path('admin/manage-users/', views.manage_users_view, name='manage_users'),
    path('admin/edit-user/<int:user_id>/', views.edit_user_view, name='edit_user'),
    path('admin/delete-user/<int:user_id>/', views.delete_user_view, name='delete_user'),
    path('admin/reset-password/<int:user_id>/', views.reset_password_view, name='reset_password'),
    path('admin/view-user/<int:user_id>/', views.view_user_details_view, name='view_user_details'),
    path('admin/system-settings/', views.system_settings_view, name='system_settings'),
    path('admin/backup-data/', views.backup_data_view, name='backup_data'),
    path('employee/', views.employee_view, name='employee'),
    path('employee/profile/', views.profile_view, name='employee_profile'),
    path('employee/leave/', views.leave_view, name='employee_leave'),
    path('employee/tasks/', views.employee_tasks_view, name='employee_tasks'),
    path('employee/tasks/<int:task_id>/submit/', views.submit_task, name='submit_task'),
    path('manager/', views.manager_view, name='manager'),
    path('manager/employees/', views.manager_employees_view, name='manager_employees'),
    path('manager/add-employee/', views.manager_add_employee_view, name='manager_add_employee'),
    path('manager/tasks/', views.manager_tasks_view, name='manager_tasks'),
    path('manager/leave/', views.manager_leave_view, name='manager_leave'),
    path('manager/attendance/', views.manager_attendance_view, name='manager_attendance'),
    path('manager/tracking/', views.employee_tracking_view, name='employee_tracking'),
    path('manager/profile/', views.manager_profile_view, name='manager_profile'),
    path('manager/own-attendance/', views.manager_own_attendance_view, name='manager_own_attendance'),
    path('manager/own-leave/', views.manager_own_leave_view, name='manager_own_leave'),
    path('manager/own-payroll/', views.manager_own_payroll_view, name='manager_own_payroll'),
    path('manager/leave/approve/<int:leave_id>/', views.approve_leave, name='approve_leave'),
    path('manager/leave/reject/<int:leave_id>/', views.reject_leave, name='reject_leave'),
    path('manager/task/create/', views.create_task, name='create_task'),
]