# Generated by Django 5.2.7 on 2025-11-01 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
