# Generated by Django 5.2.4 on 2025-10-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rule_name', models.CharField(max_length=100)),
                ('grace_minutes', models.IntegerField(default=15)),
                ('rounding_policy', models.CharField(choices=[('none', 'No Rounding'), ('nearest_15', 'Nearest 15 minutes'), ('nearest_30', 'Nearest 30 minutes')], default='none', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('logo_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkWeek',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('is_working_day', models.BooleanField(default=True)),
            ],
        ),
    ]
