# Generated by Django 5.2.4 on 2025-10-14 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('punch_type', models.CharField(choices=[('IN', 'Check In'), ('OUT', 'Check Out')], max_length=10)),
                ('punch_time', models.DateTimeField()),
                ('geo_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('geo_long', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('selfie_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='approved', max_length=20)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.device')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.employee')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceSummary',
            fields=[
                ('summary_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('in_time', models.TimeField(blank=True, null=True)),
                ('out_time', models.TimeField(blank=True, null=True)),
                ('total_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('late_by', models.IntegerField(default=0, help_text='Late by minutes')),
                ('early_out', models.IntegerField(default=0, help_text='Early out by minutes')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('half_day', 'Half Day'), ('leave', 'On Leave')], default='present', max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.employee')),
            ],
            options={
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
